# Generated by Django 5.2.16 on 2026-07-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextileWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('Cotton', 'Cotton'), ('Polyester', 'Polyester'), ('Silk', 'Silk'), ('Wool', 'Wool'), ('Denim', 'Denim')], max_length=100)),
                ('quantity', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
